from __future__ import annotations
from flask import Flask, render_template,request, jsonify, make_response, flash
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
import secrets
import hashlib
import hmac
import json
import base64
import time,datetime
from datetime import timezone
import os
from dotenv import load_dotenv

load_dotenv()

# No attempt at CSRF Protection!

app = Flask(__name__)

# Secret key for signing cookies

# Do NOT hardcode SECRET_KEY!

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=["5/minute"],
    storage_uri="memory://",
)


# SECRET_KEY should store a 16-byte string

# generated by a CSPRNG

SECRET_KEY = str(os.getenv("SECRET_KEY"))

def create_session_cookie(user_id, username, role):
	"""Create signed session cookie"""
	# Session data as JSON

	expiration_time = datetime.datetime.now(tz=timezone.utc) + datetime.timedelta(days=7)
 
	session_data = {
		'user_id': user_id,
		'username': username,
		'role': role,
		'is_admin': (role == 'admin'),
		'login_time': int(time.time()),
		'exp': int(time.time() + (86400 * 7))
		# No field marking when cookie expires
	}
	
	# Encode as base64
	session_json = json.dumps(session_data)
	session_b64 = base64.b64encode(session_json.encode()).decode()
	
	# Sign with HMAC-SHA256
	signature = hmac.new(
		SECRET_KEY.encode(),
		session_b64.encode(),
		hashlib.sha256
	).hexdigest()
	
	# Cookie value: base64_data.signature
	cookie_value = f"{session_b64}.{signature}"
	
	return cookie_value

def verify_session_cookie(cookie_value):
	"""Verify and parse session cookie"""
	if not cookie_value:
		return None

	# Must check if session cookie expired
	
	try:
		# Split cookie into data and signature
		session_b64, provided_sig = cookie_value.split('.')
		
		# Verify signature
		expected_sig = hmac.new(
			SECRET_KEY.encode(),
			session_b64.encode(),
			hashlib.sha256
		).hexdigest()

		# Timing Vulnerability Below
		
		if not hmac.compare_digest(provided_sig,expected_sig):
			
			return None

		# Decode session data
		session_json = base64.b64decode(session_b64).decode()
		
		session_data = json.loads(session_json)

		current_time = int(time.time()) 

		if current_time > session_data['exp']:

			return None
		
		return session_data
		
	except Exception as e:

		print(f"Exception: {e}")

		return None

@app.route('/login', methods=['POST'])
@limiter.limit("5/minute")
def login():
	"""User login endpoint"""
	username = request.form.get('username')
	password = request.form.get('password')
	
	# Authenticate user (assume this works correctly)
	user = authenticate_user(username, password)
	if not user:
		return jsonify({"error": "Invalid credentials"}), 401
	
	# Create session cookie
	cookie_value = create_session_cookie(
		user_id=user['id'],
		username=user['username'],
		role=user['role']
	)
	
	# Create response and set cookie
	response = make_response(jsonify({"message": "Login successful"}))
	response.set_cookie(
		'session',
		value=cookie_value,
		max_age=86400 * 7,  # 7 days
		httponly=True,
		path='/',
		secure=True,
		samesite='Strict' # This suffices as CSRF Protection

		# Secure flag missing

		# SameSite flag missing
	)
	
	return response

@app.route('/api/records', methods=['GET'])
@limiter.limit("5/minute")
def get_records():
	"""Get medical records (requires authentication)"""
	# Read session cookie
	cookie_value = request.cookies.get('session')
	session_data = verify_session_cookie(cookie_value)
	
	if not session_data:
		return jsonify({"error": "Unauthorized"}), 401
	
	# Check if user is admin
	if session_data.get('is_admin'):
		records = get_all_records()
	else:
		records = get_user_records(session_data['user_id'])
	
	return jsonify({"records": records})

@app.route('/api/admin/users', methods=['GET'])
@limiter.limit("5/minute")
def admin_get_users():
	"""Admin endpoint - get all users"""
	cookie_value = request.cookies.get('session')
	session_data = verify_session_cookie(cookie_value)
	
	if not session_data:
		return jsonify({"error": "Unauthorized"}), 401
	
	if not session_data.get('is_admin'):
		return jsonify({"error": "Forbidden"}), 403
	
	users = get_all_users()

	return jsonify({"users": users})

@app.route('/logout', methods=['POST'])
@limiter.limit("5/minute")
def logout():
	"""User logout endpoint"""
	response = make_response(jsonify({"message": "Logged out"}))
	response.set_cookie('session', '', max_age=0)
	return response

if __name__ == '__main__':

	cookie_value = create_session_cookie(1,"name","user")

	print(f"cookie_value:{cookie_value}")

	session_data = verify_session_cookie(cookie_value)
	
	print(f"session_data:{session_data}")

	app.run(host='0.0.0.0', port=8080)
